version: '3'
services:
  dev:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/sierpinski
      - node_modules:/usr/src/sierpinski/node_modules
    command: bash
  prod:
    build: .
    ports:
      - "8080:8080"

volumes:
  node_modules: